### ISSUE TITLE
Ghostext for firefox not found on firefox addons site

### ISSUE THREAD

**Issue by Azeirah** [Cacodaimon/GhostText-for-Firefox#21]
https://addons.mozilla.org/en-US/firefox/addon/ghosttext-for-firefox/

is not found

**Comment by Cacodaimon** [comment]
After waiting two and a half month it got reviewed and got rejected because it did not meet the criteria.

I had not found the time for building a new version matching the mozilla amo cirteria, but I'm optimistic that I will find the time in the next weeks.

So please be patient…

**Comment by bfred-it** [comment]
Whaaaa? What criteria wasn't met exactly?

**Comment by Cacodaimon** [comment]
```
Comments:
Your version was rejected because of the following problems:

1) Generating script fragments such as content scripts from unsanitized string data is error prone and poses a major risk of security vulnerabilities. For more information, please see https://developer.mozilla.org/en/XUL_School/DOM_Building_and_HTML_Insertion#listeners

Please fix them and submit again. Thank you.
```

**Comment by Cacodaimon** [comment]
I have uploaded a new version to Mozilla Add-ons, this can take several weeks up to months until they reviewed it again… 

Until it got reviewed by mozilla you should consider [installing the add-on manually](https://github.com/Cacodaimon/GhostText-for-Firefox#for-testers) or switch to the Chrome version ;)

**Comment by Cacodaimon** [comment]
The add-on is available again, I used the "Preliminary Review" which results in a lower ranking and a warning message during the installation but on the other hand the review process is not so strict… .

**Comment by fregante** [comment]
The new GhostText Firefox extension has been published https://addons.mozilla.org/en-US/firefox/addon/ghosttext/ :)
