### ISSUE TITLE
GhostText not working with Behave.PRO plugin

### ISSUE THREAD

**Issue by xray5483** [Cacodaimon/GhostText-for-Firefox#22]
Hi there,
I am trying to use GhostText to write with the help of sublime text editor and cusomt snippets within the editable text boxes of the Behave.PRO plugin. This plugin is integrated in JIRA and we are using it to write our automated bdd tests. The problem I face is that Ghosttext does connect to the text box and opens it up in sublime text but none of the text I type in does appear in the text box itself within JIRA. There are no connection problems it just doesn't type in what I write in sublime text. Could you please help me out with this issue?

**Comment by Cacodaimon** [comment]
Can you provide some kind of demo account for debugging?

**Comment by xray5483** [comment]
Unfortunately I cannot provide you a demo account for debugging :((. I can just tell you that the thing is within an iframe so maybe that's the issue. Here is the issue raised with the guy that created the edit in zed plugin which is similar to ghosttext. It was from that discussion that I was suggested to give ghost text a try and see if it works. There is some more detail there which might help...
